name: 'CI'
on:
  push:
  pull_request:
  schedule:
    - cron: '14 3 * * SAT'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build & Test'
        env:
          BRANCH_NAME: ${{ github.ref }}
        run: ./gradlew check -PbrancheName=$BRANCH_NAME --info
      - name: 'Publish docker image'
        if: ${{ startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/main') }}
        env:
          BRANCH_NAME: ${{ github.ref }}
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: ./gradlew pushDockerImage -PbranchName=$BRANCH_NAME --info