name: 'Scheduled Build'
on:
  schedule:
    - cron: '0/15 * * * SAT'

jobs:
  scheduledBuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, release]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build info'
        run: echo Checked out branch `${{ matrix.branch }}`. Using github.ref= ${{ github.ref }}
      - name: 'Build & Test'
        env:
          BRANCH_NAME: ${{ matrix.branch }}
        run: ./gradlew check -PbrancheName=$BRANCH_NAME --info
      - name: 'Publish docker image'
        if: ${{ endsWith(github.ref, 'release') || endsWith(github.ref, 'main') }}
        env:
          BRANCH_NAME: ${{ matrix.branch }}
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: ./gradlew pushDockerImage -PbranchName=$BRANCH_NAME --info